module.exports = (db) => {
  db.agences
    .bulkCreate([
      { id: 1, city: "DMAX SUD-OUEST (TOULOUSE)" },
      { id: 2, city: "DMAX HDF (ST AMAND)" },
      { id: 3, city: "DMAX IDF (CLICHY) " },
      { id: 4, city: "DMAX IDF (ELANCOURT et CONCHES)" },
      { id: 5, city: "DMAX SUD OUEST (MARSEILLE)" },
      { id: 6, city: "DMAX IDF (LYON)" },
      { id: 7, city: "DMAX SUD OUEST (AGEN)" },
      { id: 8, city: "DMAX SUD OUEST (GRENOBLE)" },
      { id: 9, city: "DMAX SUD OUEST (GRENADE)" },
      { id: 10, city: "DMAX SUD OUEST (MONTPELLIER et PACA)" },
    ])
    .then(() => console.log("Agences data have been saved"));

  db.directions
    .bulkCreate([
      {
        id: 1,
        name: "Direction administrative et financière France ",
      },
      { id: 2, name: "Direction commerciale France" },
      { id: 3, name: "Direction des opérations France" },
      { id: 4, name: "Direction des RHFrance" },
    ])
    .then(() => console.log("Directions data have been saved"));

  db.pilotages
    .bulkCreate([
      {
        id: 1,
        name: "Direction  ",
      },
      { id: 2, name: "DAF" },
      { id: 3, name: "QHSE" },
      { id: 4, name: "Systèmes d’informations" },
      { id: 5, name: "Commerce" },
      { id: 6, name: "Infrast. & Envir. de travail" },
      { id: 7, name: "Exploitation" },
      { id: 8, name: "Ressources Humaines" },
      { id: 9, name: "Directeur Général" },
    ])
    .then(() => console.log("Pilotages data have been saved"));

  db.services
    .bulkCreate([
      { id: 1, name: "Resp. comptable groupe " },
      { id: 2, name: "Gestionnaires ADV" },
      { id: 3, name: "Contrôleurs de gestion" },
      { id: 4, name: "Directeur Achats " },
      { id: 5, name: "DSI " },
      { id: 6, name: "Commerciaux DMAX IDF/AURA,  DMAX SO et DMAX HDF" },
      { id: 7, name: "Responsables d’exploitations" },
      { id: 8, name: "Coordinateurs" },
      { id: 9, name: "Chefs d’équipes / Contremaîtres" },
      { id: 10, name: "Déménageurs" },
      { id: 11, name: "Chargée SIAE" },
      { id: 12, name: "Gestionnaires RH" },
      { id: 13, name: "Responsable paie" },
      { id: 14, name: "Responsable QHSE" },
      { id: 15, name: "Gestionnaire parc roulant" },
      { id: 16, name: "Gestion immobilière" },
      { id: 17, name: "PDG DMAX France" },
      { id: 18, name: "Chef" },
    ])
    .then(() => console.log("Services data have been saved"));
  db.tags
    .bulkCreate([
      { id: 1, name: "Téléphonie" },
      { id: 2, name: "Route" },
      { id: 3, name: "Grand Compte" },
      // { id: 4, name: "Téléphonie 1" },
      // { id: 5, name: "Route 1" },
      // { id: 6, name: "Grand Compte 1" },
      // { id: 7, name: "Téléphonie 2" },
      // { id: 8, name: "Route 2" },
      // { id: 9, name: "Grand Compte 2" },
    ])
    .then(() => console.log("Tag data have been saved"));

  db.employees
    .bulkCreate([
      {
        id: 1,
        name: "AMATO",
        surname: "Franck",
        email: "franck.amato@dmax.fr",
        mobilefixe: "05 67 20 21 41",
        mobile: "06 31 33 63 75",
        image: "public/uploads/AMATO_Franck-1674544358939.jpeg",
        active: 1,
        AgenceId: 9,
        ServicesActiviteId: 18,
        PilotageId: null,
        DirectionId: 4,
      },
      {
        id: 2,
        name: "UFARTE",
        surname: "Olivier",
        email: "olivier.ufarte@dmax.fr",
        mobilefixe: "05 61 47 87 17",
        mobile: "06 76 98 54 22",
        image: "public/uploads/UFARTE_Olivier-1674544824359.jpeg",
        active: 1,
        AgenceId: 9,
        ServicesActiviteId: 5,
        PilotageId: null,
        DirectionId: 1,
      },
      // {
      //   id: 3,
      //   name: "AUGEREAU",
      //   surname: "Rudy",
      //   email: "rudy.augereau@dmax.fr",
      //   mobilefixe: null,
      //   mobile: "07 86 07 80 47",
      //   image: "public/uploads/AUGEREAU_Rudy-1674552505177.jpeg",
      //   active: 1,
      //   AgenceId: 3,
      //   ServicesActiviteId: 6,
      //   PilotageId: null,
      //   DirectionId: 2,
      // },
      {
        id: 4,
        name: "DELATTRE",
        surname: "François-Xavier",
        email: "francois-xavier.delattre@dmax.fr",
        mobilefixe: " ",
        mobile: "06 27 70 56 70",
        image: "public/uploads/DELATTRE_François-Xavier-1674544166286.jpeg",
        active: 1,
        AgenceId: 3,
        ServicesActiviteId: 18,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 5,
        name: "JAMAN",
        surname: "Jérome ",
        email: "jerome.jaman@dmax.fr",
        mobilefixe: "01 84 78 88 80",
        mobile: "06 19 14 49 38",
        image: "public/uploads/Jaman_Jérome -1674543874989.jpeg",
        active: 1,
        AgenceId: 3,
        ServicesActiviteId: 17,
        PilotageId: null,
        DirectionId: null,
      },

      {
        id: 6,
        name: "JAMAN",
        surname: "Julien",
        email: "julien.jaman@dmax.fr",
        mobilefixe: "01 84 78 88 88",
        mobile: "06 61 82 29 61",
        image: "public/uploads/Jaman_Julien-1674543776644.jpeg",
        active: 1,
        AgenceId: 3,
        ServicesActiviteId: null,
        PilotageId: 9,
        DirectionId: null,
      },
      // Fin HomePage

      //DEBUT Page direction admin
      {
        id: 7,
        name: "DESTRINGUET",
        surname: "Cindy",
        email: "cindy.destringuet@dmax.fr",
        mobilefixe: " 03 27 48 30 36 ",
        mobile: " ",
        image: "public/uploads/DESTRINGUET_Cindy-1674555329236.jpeg",
        active: 1,
        AgenceId: 2,
        ServicesActiviteId: 2,
        PilotageId: null,
        DirectionId: 1,
      },
      
      {
        id: 8,
        name: "TRUPPNER",
        surname: "Evelyne",
        email: "evelyne.truppner@dmax.fr",
        mobilefixe: " 05 61 47 89 87 ",
        mobile: " ",
        image: "public/uploads/WOMAN_Woman-1674556887979.jpeg ",
        active: 1,
        AgenceId: 9,
        ServicesActiviteId: 2,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 9,
        name: "VALLES",
        surname: "Sandrine",
        email: "sandrine.valles@dmax.fr",
        mobilefixe: " 05 67 20 21 46 ",
        mobile: " 06 07 24 76 95",
        image: "public/uploads/VALLES_Sandrine-1674555778231.jpeg ",
        active: 1,
        AgenceId: 9,
        ServicesActiviteId: 2,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 10,
        name: "JAMAN",
        surname: "Géraldine",
        email: "geraldine.jaman@dmax.fr",
        mobilefixe: " 01 84 78 88 85 ",
        mobile: " 06 26 33 66 95",
        image: "public/uploads/JAMAN_Géraldine-1674555846902.jpeg ",
        active: 1,
        AgenceId: 3,
        ServicesActiviteId: 2,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 11,
        name: "CHASSOT",
        surname: "bruno",
        email: "bruno.chassot@dmax.fr",
        mobilefixe: " 01 84 78 88 86 ",
        mobile: " 06 60 34 19 72",
        image: "public/uploads/CHASSOT_Bruno-1674555968063.jpeg ",
        active: 1,
        AgenceId: 3,
        ServicesActiviteId: 4,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 12,
        name: "JOSSE",
        surname: "Julie",
        email: "julie.josse@dmax.fr",
        mobilefixe: " 01 84 78 88 98 ",
        mobile: " ",
        image: "public/uploads/JOSSE_Julie-1674556283264.jpeg",
        active: 1,
        AgenceId: 3,
        ServicesActiviteId: 3,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 13,
        name: "ADER",
        surname: "Benjamin",
        email: "benjamin.ader@dmax.fr",
        mobilefixe: "  05 67 20 21 41 ",
        mobile: " 06 31 33 63 75 ",
        image: "public/uploads/ADER_Benjamin-1674556414959.jpeg",
        active: 1,
        AgenceId: 9,
        ServicesActiviteId: 3,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 14,
        name: "GARNIER",
        surname: "Réjane",
        email: "rejane.garnier@dmax.fr",
        mobilefixe: "  01 84 78 88 87 ",
        mobile: " ",
        image: "public/uploads/GARNIER_Rejane-1674557179821.jpeg",
        active: 1,
        AgenceId: 3,
        ServicesActiviteId: 1,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 15,
        name: "MAROCCO",
        surname: "Carole",
        email: "carole.marocco@dmax.fr",
        mobilefixe: "  05 67 20 35 12 ",
        mobile: " ",
        image: "public/uploads/MAROCCO_Carole-1674557278818.jpeg",
        active: 1,
        AgenceId: 9,
        ServicesActiviteId: 1,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 16,
        name: "SEGAILLAT",
        surname: "Nathaly",
        email: "nathaly.segaillat@dmax.fr",
        mobilefixe: "  05 61 47 73 53 ",
        mobile: " ",
        image: "public/uploads/SEGAILLAT_Nathaly-1674557372911.jpeg",
        active: 1,
        AgenceId: 9,
        ServicesActiviteId: 1,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 17,
        name: "BLOMME",
        surname: "Lydie",
        email: "lydie.blomme@dmax.fr",
        mobilefixe: " 03 27 48 30 41 ",
        mobile: " ",
        image: "public/uploads/BLOMME_Lydie-1674557498299.jpeg",
        active: 1,
        AgenceId: 2,
        ServicesActiviteId: 1,
        PilotageId: null,
        DirectionId: 1,
      },
      {
        id: 18,
        name: "JAMAN",
        surname: "Julien",
        email: "julien.jaman@dmax.fr",
        mobilefixe: "01 84 78 88 88",
        mobile: "06 61 82 29 61",
        image: "public/uploads/Jaman_Julien-1674543776644.jpeg",
        active: 1,
        AgenceId: 3,
        ServicesActiviteId: 18,
        PilotageId: null,
        DirectionId: 2,
      },

      
      
    ])
    .then(() => console.log("Employee data have been saved"));

  db.employees_tags
    .bulkCreate([
      { EmployeeId: 1, TagId: 1 },
      { EmployeeId: 1, TagId: 2 },
      { EmployeeId: 1, TagId: 3 }
    ])
  .then(() => console.log("TagID data have been saved"));

  db.services_direction
    .bulkCreate([
      // Chief
      { id: 1, DirectionId: 1, ServicesActiviteId: 18 },
      { id: 2, DirectionId: 2, ServicesActiviteId: 18 },
      { id: 3, DirectionId: 3, ServicesActiviteId: 18 },
      { id: 4, DirectionId: 4, ServicesActiviteId: 18 },
      // association 1 direction
      { id: 6, DirectionId: 1, ServicesActiviteId: 1 },
      { id: 7, DirectionId: 1, ServicesActiviteId: 2 },
      { id: 8, DirectionId: 1, ServicesActiviteId: 3 },
      { id: 9, DirectionId: 1, ServicesActiviteId: 4 },
      { id: 10, DirectionId: 1, ServicesActiviteId: 5 },
      //2eme
      { id: 21, DirectionId: 2, ServicesActiviteId: 6 },
      { id: 11, DirectionId: 2, ServicesActiviteId: 7 },
      { id: 12, DirectionId: 3, ServicesActiviteId: 8 },
      { id: 13, DirectionId: 3, ServicesActiviteId: 9 },
      { id: 14, DirectionId: 3, ServicesActiviteId: 10 },
      { id: 15, DirectionId: 3, ServicesActiviteId: 11 },
      // Troisieme
      { id: 16, DirectionId: 4, ServicesActiviteId: 12 },
      { id: 17, DirectionId: 4, ServicesActiviteId: 13 },
      { id: 18, DirectionId: 4, ServicesActiviteId: 14 },
      { id: 19, DirectionId: 4, ServicesActiviteId: 15 },
      { id: 20, DirectionId: 4, ServicesActiviteId: 16 },
    ])
    .then(() => console.log("Services_Directions data have been saved"));
};
